import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {

  const [animeList, setAnimeList] = useState<any[]>([]);

  useEffect(() => {
    const subscribe = async () => {
      const response = await fetch('http://api.moemoe.tokyo/anime/v1/master/2021/2');

      const data = await response.json();
      setAnimeList(data);
    }

    subscribe();
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>アニメ一覧</h1>
      <p>シーズンごとにアニメの一覧を見れるよ！</p>
      <ul>
        {
          animeList.map((anime, index) => {
            return <li key={index}>{anime.title}</li>
          })
        }
      </ul>
    </div>
  )
}

export default Home
